USE [master]
GO
/****** Object:  Database [DB_Expresiones]    Script Date: 11/11/2022 17:16:44 ******/
CREATE DATABASE [DB_Expresiones]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_Expresiones', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DB_Expresiones.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_Expresiones_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DB_Expresiones_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DB_Expresiones] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_Expresiones].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_Expresiones] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_Expresiones] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_Expresiones] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_Expresiones] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_Expresiones] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_Expresiones] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_Expresiones] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_Expresiones] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_Expresiones] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_Expresiones] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_Expresiones] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_Expresiones] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_Expresiones] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_Expresiones] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_Expresiones] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DB_Expresiones] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_Expresiones] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_Expresiones] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_Expresiones] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_Expresiones] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_Expresiones] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_Expresiones] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_Expresiones] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DB_Expresiones] SET  MULTI_USER 
GO
ALTER DATABASE [DB_Expresiones] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_Expresiones] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_Expresiones] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_Expresiones] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_Expresiones] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_Expresiones] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DB_Expresiones] SET QUERY_STORE = OFF
GO
USE [DB_Expresiones]
GO
/****** Object:  Table [dbo].[Lista_Expresiones]    Script Date: 11/11/2022 17:16:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lista_Expresiones](
	[idExpresiones] [int] IDENTITY(1,1) NOT NULL,
	[Expresion] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Lista_Expresiones] PRIMARY KEY CLUSTERED 
(
	[idExpresiones] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Lista_Expresiones] ON 
GO
INSERT [dbo].[Lista_Expresiones] ([idExpresiones], [Expresion]) VALUES (1, N'45/56*7   ')
GO
INSERT [dbo].[Lista_Expresiones] ([idExpresiones], [Expresion]) VALUES (2, N'45-96/0   ')
GO
INSERT [dbo].[Lista_Expresiones] ([idExpresiones], [Expresion]) VALUES (3, N'34+89*78  ')
GO
SET IDENTITY_INSERT [dbo].[Lista_Expresiones] OFF
GO
USE [master]
GO
ALTER DATABASE [DB_Expresiones] SET  READ_WRITE 
GO
