USE [master]
GO
/****** Object:  Database [db_prueba]    Script Date: 10/11/2022 18:30:56 ******/
CREATE DATABASE [db_prueba]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_prueba', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\db_prueba.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_prueba_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\db_prueba_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [db_prueba] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_prueba].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db_prueba] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_prueba] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_prueba] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_prueba] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_prueba] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_prueba] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db_prueba] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_prueba] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_prueba] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_prueba] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_prueba] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_prueba] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_prueba] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_prueba] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_prueba] SET  DISABLE_BROKER 
GO
ALTER DATABASE [db_prueba] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_prueba] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_prueba] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_prueba] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_prueba] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_prueba] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db_prueba] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db_prueba] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [db_prueba] SET  MULTI_USER 
GO
ALTER DATABASE [db_prueba] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_prueba] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db_prueba] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db_prueba] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_prueba] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db_prueba] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [db_prueba] SET QUERY_STORE = OFF
GO
USE [db_prueba]
GO
/****** Object:  Table [dbo].[tabla_nomames]    Script Date: 10/11/2022 18:30:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tabla_nomames](
	[idnomames] [int] NOT NULL,
	[expresion] [nchar](10) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[tabla_nomames] ([idnomames], [expresion]) VALUES (1, N'767       ')
GO
INSERT [dbo].[tabla_nomames] ([idnomames], [expresion]) VALUES (4, N'567       ')
GO
INSERT [dbo].[tabla_nomames] ([idnomames], [expresion]) VALUES (156, N'772+34    ')
GO
INSERT [dbo].[tabla_nomames] ([idnomames], [expresion]) VALUES (45, N'89+90/35  ')
GO
ALTER TABLE [dbo].[tabla_nomames] ADD  CONSTRAINT [DF_tabla_nomames_idnomames]  DEFAULT ((1)) FOR [idnomames]
GO
USE [master]
GO
ALTER DATABASE [db_prueba] SET  READ_WRITE 
GO
